#!/bin/bash

set -ex

#Create groestlcoin.conf if it doesn't exist
if [ ! -e "/root/.groestlcoin/groestlcoin.conf" ]; then
    mkdir -p /root/.groestlcoin

	echo "groestlcoin.conf doesn't exist; creating."

	cat <<EOF > /root/.groestlcoin/groestlcoin.conf
disablewallet=1
printtoconsole=1
rpcuser=groestlcoinrpc
rpcpassword=`dd if=/dev/urandom bs=33 count=1 2>/dev/null | base64`
EOF

fi

exec groestlcoind
